name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, xml, bcmath, json, fileinfo

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add cPanel server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 7822 restapi.nayan.pro >> ~/.ssh/known_hosts

      - name: Copy files to cPanel via SCP
        run: |
          export LANG=en_US.UTF-8
          export LC_ALL=en_US.UTF-8
          scp -P 7822 -r -o StrictHostKeyChecking=no ./* nayan@restapi.nayan.pro:/home/nayan/restapi.nayan.pro

